{% set name = "arcosparse" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arcosparse-{{ version }}.tar.gz
  sha256: 126f1736596712df51a1b88c7d93d50d79d44ec0193b56e2d518fec5cf12fe13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.27.1,<3.0.0
    - pandas >=2.0.0
    - pystac >=1.8.3,<2.0.0
    - pyarrow >=17.0.0
    - tqdm >=4.65.0,<5.0.0

test:
  imports:
    - arcosparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://pypi.org/project/arcosparse/
  summary: Helper to download and subset sparse data that has been Arcoified and are available through STAC and sqlite formated data
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renaudjester
    - uriii3
    - jordi-domingo
    - Theophile-Varnier
